spring:
  application:
    name: computador
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:prova_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
